name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Verify Next.js installation
        run: npm list next

      - name: Print working directory
        run: pwd

      - name: List files in the project directory
        run: ls -la

      - name: List node modules
        run: ls -la node_modules

      - name: Run tests
        run: npm run test
